import fs from 'fs';
const updates: Record<string, any[]> = {
  "honda-cb300-2013-2014": [
    { pin: "1", color: "Preto/Azul", function: "POSITIVO PÓS CHAVE 12V" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL SENSOR OXIGENIO" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO SENSORES: TP/MAP/IAT/INCLINAÇÃO/EOT/OXIGENIO" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO 5V PARA SENSORES: TP/MAP/INCLINAÇÃO" },
    { pin: "7", color: "Amarelo/Verde", function: "SINAL TACOMETRO PARA PAINEL" },
    { pin: "8", color: "Marrom", function: "SINAL NEGATIVO DA ECM PARA RELÉ BOMBA COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "11", color: "Amarelo/Azul", function: "SINAL NEGATIVO DA ECM PARA BOBINA DE IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "POSITIVO SENSOR CKP" },
    { pin: "13", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "14", color: "Cinza/Azul", function: "SINAL DO SENSOR IAT PARA ECM" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Azul", function: "SINAL NEGATIVO DA ECM PARA O BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Marrom/Preto", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A" },
    { pin: "21", color: "Azul/Laranja", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A" },
    { pin: "22", color: "Branco/Preto", function: "PULSO PWM PARA RESISTENCIA AQUECEDOR SENSOR OXIGENIO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "POSITIVO/SINAL DO SENSOR EOT" },
    { pin: "25", color: "Verde/Branco", function: "SINAL NEGATIVO DO INTERRUPTOR CAVALETE LATERAL." },
    { pin: "26", color: "Verde/Vermelho", function: "SINAL SENSOR INCLINAÇÃO PARA ECM" },
    { pin: "27", color: "Vermelho/Amarelo", function: "SINAL DO SENSOR MAP PARA ECM" },
    { pin: "28", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "29", color: "Rosa/Verde", function: "INTERRUPTOR DE PONTO MORTO" },
    { pin: "30", color: "Verde/Branco", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Azul/Vermelho", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B" },
    { pin: "32", color: "Azul/Branco", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B" },
    { pin: "33", color: "Preto/Azul", function: "INDICADOR PARTIDA A FRIO" }
  ],
  "honda-cb300-2015-limited": [
    { pin: "1", color: "Preto/Marrom", function: "POSITIVO PÓS CHAVE 12V" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL SENSOR OXIGENIO" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO SENSORES: TP/MAP/IAT/INCLINAÇÃO/EOT/OXIGENIO" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO 5V PARA SENSORES: TP/MAP/INCLINAÇÃO" },
    { pin: "7", color: "Amarelo/Verde", function: "SINAL TACOMETRO PARA PAINEL" },
    { pin: "8", color: "Marrom", function: "SINAL NEGATIVO DA ECM PARA RELÉ BOMBA COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "11", color: "Rosa/Azul", function: "SINAL NEGATIVO DA ECM PARA BOBINA DE IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "POSITIVO SENSOR CKP" },
    { pin: "13", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "14", color: "Cinza/Azul", function: "SINAL DO SENSOR IAT PARA ECM" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Azul", function: "SINAL NEGATIVO DA ECM PARA O BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Marrom/Preto", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A" },
    { pin: "21", color: "Azul/Laranja", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A" },
    { pin: "22", color: "Branco/Preto", function: "PULSO PWM PARA RESISTENCIA AQUECEDOR SENSOR OXIGENIO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "POSITIVO/SINAL DO SENSOR EOT" },
    { pin: "25", color: "Verde/Branco", function: "SINAL NEGATIVO DO INTERRUPTOR CAVALETE LATERAL." },
    { pin: "26", color: "Verde/Vermelho", function: "SINAL SENSOR INCLINAÇÃO PARA ECM" },
    { pin: "27", color: "Vermelho/Amarelo", function: "SINAL DO SENSOR MAP PARA ECM" },
    { pin: "28", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "29", color: "Rosa/Verde", function: "INTERRUPTOR DE PONTO MORTO" },
    { pin: "30", color: "Verde/Branco", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Azul/Vermelho", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B" },
    { pin: "32", color: "Azul/Branco", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B" },
    { pin: "33", color: "Preto/Azul", function: "INDICADOR PARTIDA A FRIO" }
  ],
  "honda-cb300f-twister-2023-2024": [
    { pin: "1", color: "Preto/Branco", function: "POSITIVO PÓS CHAVE PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO SENSORES: TP/MAP/IAT/INCLINAÇÃO/EOT/OXIGENIO" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL SAIDA DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "5V ALIMENTAÇÃO SENSOR INCLINAÇÃO E UNIDADE SENSORES (MAP, TPS E IAT)" },
    { pin: "7", color: "Rosa/Verde", function: "SINAL DO TACOMETRO DO PAINEL" },
    { pin: "8", color: "Marrom", function: "NEGATIVO DA ECM PARA O RELÉ DA BOMBA COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "11", color: "Amarelo/Azul", function: "NEGATIVO ECM PARA BOBINA DE IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA POSITIVO DO SENSOR CKP PARA O ECM" },
    { pin: "13", color: "Amarelo/Branco", function: "SINAL SENSOR COMBUSTIVEL" },
    { pin: "14", color: "Cinza/Azul", function: "SINAL DE SAIDA DO SENSOR IAT DA UNIDADE DE SENSORES PARA O ECM" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "LUZ LAMPADA FI NO PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Marrom/Preto", function: "PULSO NEGATIVO AQUECEDOR SENSOR O²" },
    { pin: "21", color: "Azul/Laranja", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A" },
    { pin: "22", color: "Azul/Branco", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "SINAL/ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Verde/Branco", function: "SINAL INTERRUPTOR DO CAVALETE LATERAL/INTERRUPTOR EMBREAGEM" },
    { pin: "26", color: "Verde/Vermelho", function: "SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM" },
    { pin: "27", color: "Vermelho/Amarelo", function: "SINAL DE SAIDA DO SENSOR MAP PARA O ECM" },
    { pin: "28", color: "Verde/Amarelo", function: "LUZ ALC PARA O PAINEL" },
    { pin: "29", color: "Rosa/Verde", function: "SINAL NEGATIVO DO INT POSIÇÃO MARCHA/PONTO MORTO PARA O ECM" },
    { pin: "30", color: "Laranja/Azul", function: "VAI PARA O CONECTOR DLC E LUZ ABS" },
    { pin: "31", color: "Marrom/Branco", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B" },
    { pin: "32", color: "Marrom/Vermelho", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A" },
    { pin: "33", color: "Vazio", function: "SEM FUNÇÃO" }
  ],
  "honda-cg125i-fan-cargo-2016-2018": [
    { pin: "1", color: "Preto/Azul", function: "VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO VAI PARA O SENSOR EOT" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL SENSOR TP" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO POSITIVA 5V SENSOR INCLINAÇÃO E SENSOR TP" },
    { pin: "7", color: "Vazio", function: "TERRA NEGATIVO RELE DE CARGA" },
    { pin: "8", color: "Marrom", function: "ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "11", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA DO SENSOR CKP PARA O ECM" },
    { pin: "13", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "14", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Verde", function: "ALIMENTAÇÃO NEGATIVA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "21", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "22", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "26", color: "Vermelho/Amarelo", function: "SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM" },
    { pin: "27", color: "Vazio", function: "SINAL DE SAIDA DO SENSOR MAP DA UNIDADE DE SENSORES PARA O ECM" },
    { pin: "28", color: "Vazio", function: "SINAL NEGATIVO PARA O ALC INFORMANDO MISTURA DE COMBUSTIVEL" },
    { pin: "29", color: "Verde/Vermelho", function: "SINAL NEGATIVO DO INTERRUPTOR DE EMBREAGEM E PONTO MORTO PARA O ECM" },
    { pin: "30", color: "Amarelo/Verde", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Verde", function: "NEGATIVO SENSOR TP" },
    { pin: "32", color: "Verde/Laranja", function: "NEGATIVO SENSOR DE INCLINAÇÃO" },
    { pin: "33", color: "Vazio", function: "SEM FUNÇÃO" }
  ],
  "honda-cg-start-150-2015": [
    { pin: "1", color: "Preto/Azul", function: "PÓS CHAVE 12V PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO TERRA/CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO VAI PARA O SENSOR EOT, MAP, O2, TP E IAT" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL DE SAIDA DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO 5V SENSOR MAP E TP" },
    { pin: "7", color: "Marrom/Preto", function: "ALIMENTAÇÃO NEGATIVA DO RELÉ DE CARGA" },
    { pin: "8", color: "Marrom", function: "ALIMENTAÇÃO NEGATIVA BOMBA COBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO TERRA/CHASSI" },
    { pin: "10", color: "Verde", function: "NEGATIVO TERRA/CHASSI" },
    { pin: "11", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA DO SENSOR CKP PARA O ECM" },
    { pin: "13", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "14", color: "Cinza/Azul", function: "SINAL DE SAIDA DO SENSOR IAT PARA O ECM" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Verde", function: "ALIMENTAÇÃO NEGATIVA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Marrom/Branco", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A" },
    { pin: "21", color: "Azul/Laranja", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A" },
    { pin: "22", color: "Branco/Preto", function: "SINAL PWM PARA AQUECEDOR SENSOR OXIGENIO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "26", color: "Vermelho/Amarelo", function: "SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM" },
    { pin: "27", color: "Verde/Amarelo", function: "SINAL DE SAIDA DO SENSOR MAP PARA O ECM" },
    { pin: "28", color: "Rosa/Verde", function: "LUZ ALC DO PAINEL" },
    { pin: "29", color: "Verde/Vermelho", function: "INTERRUPTOR EMBREAGEM/DIODO/NEUTRO" },
    { pin: "30", color: "Amarelo/Verde", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Marrom/Vermelho", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B" },
    { pin: "32", color: "Azul/Vermelho", function: "ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B" },
    { pin: "33", color: "Vazio", function: "SEM FUNÇÃO" }
  ]
};

let content = fs.readFileSync('src/data/hondaPinouts.ts', 'utf8');
for (const [id, pinout] of Object.entries(updates)) {
  const modelRegex = new RegExp(`(id:\\s*"${id}"[\\s\\S]*?pinout:\\s*)\\[\\]`);
  const pinoutStr = JSON.stringify(pinout, null, 10).replace(/\\n/g, '\\n        ');
  content = content.replace(modelRegex, `$1${pinoutStr}`);
}
fs.writeFileSync('src/data/hondaPinouts.ts', content);
console.log('Batch 1 applied');
