import * as fs from 'fs';
import * as path from 'path';

const file = path.join(process.cwd(), 'src/data/hondaPinouts.ts');
let content = fs.readFileSync(file, 'utf8');

const updates: Record<string, any[]> = {
  "honda-titan-160-2016-2017": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR EOT, MAP, O2 E IAT' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DE CARGA' },
    { pin: 8, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA BOMBA DE COBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: [], description: 'SINAL PWM PARA AQUECEDOR SENSOR OXIGENIO' },
    { pin: 23, color: ['Amarelo'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'LUZ ALC DO PAINEL' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/DIODO/NEUTRO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-titan-160-2018-2021": [
    { pin: 1, color: ['Preto', 'Branco'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR TP' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR EOT PARA O ECM' },
    { pin: 15, color: ['Marrom'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: [], description: 'SEM FUNÇÃO' },
    { pin: 21, color: [], description: 'SEM FUNÇÃO' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Verde'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: [], description: 'SEM FUNÇÃO' },
    { pin: 28, color: ['Amarelo', 'Preto'], description: 'SINAL NEGATIVO ECM VALVULA SOLENOIDE CONT. DE MARCHA LENTA' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/DIODO/NEUTRO' },
    { pin: 30, color: ['Laranja', 'Branco'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Verde'], description: 'NEGATIVO VAI PARA O SENSOR EOT E SENSOR DE INCLINAÇÃO' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'LUZ ALC DO PAINEL' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-titan-160-2022": [
    { pin: 1, color: ['Preto', 'Branco'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR TP' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR EOT PARA O ECM' },
    { pin: 15, color: ['Marrom'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: [], description: 'SEM FUNÇÃO' },
    { pin: 21, color: [], description: 'SEM FUNÇÃO' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Verde'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: [], description: 'SEM FUNÇÃO' },
    { pin: 28, color: ['Amarelo', 'Preto'], description: 'SINAL NEGATIVO ECM VALVULA SOLENOIDE CONT. DE MARCHA LENTA' },
    { pin: 29, color: ['Laranja', 'Amarelo'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 30, color: ['Laranja', 'Branco'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Verde'], description: 'NEGATIVO VAI PARA O SENSOR EOT / SENSOR DE INCLINAÇÃO E SENSOR O²' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'LUZ ALC DO PAINEL' },
    { pin: 33, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/DIODO/NEUTRO' }
  ],
  "honda-titan-160-2023-2024": [
    { pin: 1, color: ['Preto', 'Branco'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR TP' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR EOT PARA O ECM' },
    { pin: 15, color: ['Marrom'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: [], description: 'SEM FUNÇÃO' },
    { pin: 21, color: [], description: 'SEM FUNÇÃO' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Verde'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: [], description: 'SEM FUNÇÃO' },
    { pin: 28, color: ['Amarelo', 'Preto'], description: 'SINAL NEGATIVO ECM VALVULA SOLENOIDE CONT. DE MARCHA LENTA' },
    { pin: 29, color: ['Laranja', 'Amarelo'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 30, color: ['Laranja', 'Branco'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Verde'], description: 'NEGATIVO VAI PARA O SENSOR EOT / SENSOR DE INCLINAÇÃO E SENSOR O²' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'LUZ ALC DO PAINEL' },
    { pin: 33, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/DIODO/NEUTRO' }
  ],
  "honda-xre-190-2016-2021": [
    { pin: 1, color: ['Preto', 'Branco'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR TP' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR EOT PARA O ECM' },
    { pin: 15, color: ['Marrom'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: [], description: 'SEM FUNÇÃO' },
    { pin: 21, color: [], description: 'SEM FUNÇÃO' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Verde'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: [], description: 'SEM FUNÇÃO' },
    { pin: 28, color: ['Amarelo', 'Preto'], description: 'SINAL NEGATIVO ECM VALVULA SOLENOIDE CONT. DE MARCHA LENTA' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/DIODO/NEUTRO' },
    { pin: 30, color: ['Laranja', 'Branco'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Verde'], description: 'NEGATIVO VAI PARA O SENSOR EOT / SENSOR INCLINAÇÃO / ABS' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'LUZ ALC DO PAINEL' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-xre-190-2022-2024": [
    { pin: 1, color: ['Preto', 'Branco'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR TP' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI / DLC' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR EOT PARA O ECM' },
    { pin: 15, color: ['Marrom'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL E ABS' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: [], description: 'SEM FUNÇÃO' },
    { pin: 21, color: [], description: 'SEM FUNÇÃO' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Verde'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: [], description: 'SEM FUNÇÃO' },
    { pin: 28, color: ['Amarelo', 'Preto'], description: 'SINAL NEGATIVO ECM VALVULA SOLENOIDE CONT. DE MARCHA LENTA' },
    { pin: 29, color: ['Laranja', 'Amarelo'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 30, color: ['Laranja', 'Branco'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Verde'], description: 'NEGATIVO VAI PARA O SENSOR EOT / SENSOR DE INCLINAÇÃO / SENSOR O²' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'LUZ ALC DO PAINEL' },
    { pin: 33, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/DIODO/NEUTRO' }
  ],
  "honda-xre-300-2010-2012": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR EOT, MAP E SENSOR IAT E SENSOR DE INCLINAÇÃO' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO, MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'SINAL PWM AQUECEDOR SENSOR DE OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Vermelho', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'LUZ DO ALC PAINEL' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR DE EMBREAGEM/INTERRUPTOR NEUTRO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-xre-300-2013-2015": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR EOT, MAP E SENSOR IAT E SENSOR DE INCLINAÇÃO' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO, MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC E LUZ DO ABS' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'SINAL PWM AQUECEDOR SENSOR DE OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Vermelho', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'LUZ DO ALC PAINEL' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR DE EMBREAGEM/INTERRUPTOR NEUTRO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-xre-300-2016-2021": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR EOT, MAP E SENSOR IAT E SENSOR DE INCLINAÇÃO' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO, MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC E LUZ DO ABS' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'SINAL PWM AQUECEDOR SENSOR DE OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'LUZ DO ALC PAINEL' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR DE EMBREAGEM/INTERRUPTOR NEUTRO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-xre-300-2022-2023": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR EOT, MAP E SENSOR IAT E SENSOR DE INCLINAÇÃO' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO, MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC E LUZ DO ABS' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'SINAL PWM AQUECEDOR SENSOR DE OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'LUZ DO ALC PAINEL' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR DE EMBREAGEM/INTERRUPTOR NEUTRO/DIODO DO RELE DE PARTIDA' },
    { pin: 30, color: ['Laranja', 'Branco'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ]
};

for (const [id, pinout] of Object.entries(updates)) {
  const searchRegex = new RegExp(`(id: "${id}",[\\s\\S]*?name: "Módulo de Injeção Eletrônica \\(ECM\\)",\\s*pinout: )\\[\\]`);
  
  const pinoutStr = "[\n" + pinout.map(p => {
    return `          { pin: ${p.pin}, color: ${JSON.stringify(p.color)}, description: ${JSON.stringify(p.description)} }`;
  }).join(",\n") + "\n        ]";

  content = content.replace(searchRegex, `$1${pinoutStr}`);
}

fs.writeFileSync(file, content);
console.log("Done updating pinouts batch 5.");
