import fs from 'fs';
const updates: Record<string, any[]> = {
  "honda-cg-start-160-2018": [
    { pin: "1", color: "Preto/Azul", function: "VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO VAI PARA O SENSOR EOT" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL DE SAIDA DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO E SENSOR TP" },
    { pin: "7", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "8", color: "Marrom", function: "ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "11", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA DO SENSOR CKP PARA O ECM" },
    { pin: "13", color: "Rosa/Branco", function: "IMOBILIZADOR VEM DA CHAVE IGNIÇÃO" },
    { pin: "14", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Verde", function: "ALIMENTAÇÃO NEGATIVA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "21", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "22", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "26", color: "Vermelho/Amarelo", function: "SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM" },
    { pin: "27", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "28", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "29", color: "Verde/Vermelho", function: "SINAL NEGATIVO DO INTERRUPTOR DE EMBREAGEM E PONTO MORTO PARA O ECM" },
    { pin: "30", color: "Amarelo/Verde", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Verde", function: "NEGATIVO SENSOR TP" },
    { pin: "32", color: "Verde/Laranja", function: "NEGATIVO SENSOR DE INCLINAÇÃO" },
    { pin: "33", color: "Vazio", function: "SEM FUNÇÃO" }
  ],
  "honda-cg-start-160-2019-2020-diodo": [
    { pin: "1", color: "Preto/Azul", function: "VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO VAI PARA O SENSOR EOT" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL DE SAIDA DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO E SENSOR TP" },
    { pin: "7", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "8", color: "Marrom", function: "ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "11", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA DO SENSOR CKP PARA O ECM" },
    { pin: "13", color: "Rosa/Preto", function: "IMOBILIZADOR VEM DA CHAVE IGNIÇÃO" },
    { pin: "14", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Verde", function: "ALIMENTAÇÃO NEGATIVA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "21", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "22", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "26", color: "Vermelho/Amarelo", function: "SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM" },
    { pin: "27", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "28", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "29", color: "Verde/Vermelho", function: "SINAL NEGATIVO DO INTERRUPTOR DE EMBREAGEM E PONTO MORTO PARA O ECM" },
    { pin: "30", color: "Amarelo/Verde", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Verde", function: "NEGATIVO SENSOR TP" },
    { pin: "32", color: "Verde/Laranja", function: "NEGATIVO SENSOR DE INCLINAÇÃO" },
    { pin: "33", color: "Vazio", function: "SEM FUNÇÃO" }
  ],
  "honda-cg-start-160-2021-resistor": [
    { pin: "1", color: "Preto/Azul", function: "VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO VAI PARA O SENSOR EOT" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL DE SAIDA DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO E SENSOR TP" },
    { pin: "7", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "8", color: "Marrom", function: "ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "11", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA DO SENSOR CKP PARA O ECM" },
    { pin: "13", color: "Rosa/Azul", function: "IMOBILIZADOR VEM DA CHAVE IGNIÇÃO" },
    { pin: "14", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Verde", function: "ALIMENTAÇÃO NEGATIVA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "21", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "22", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "26", color: "Vermelho/Amarelo", function: "SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM" },
    { pin: "27", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "28", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "29", color: "Verde/Vermelho", function: "SINAL NEGATIVO DO INTERRUPTOR DE EMBREAGEM E PONTO MORTO PARA O ECM" },
    { pin: "30", color: "Amarelo/Verde", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Verde", function: "NEGATIVO SENSOR TP" },
    { pin: "32", color: "Verde/Laranja", function: "NEGATIVO SENSOR DE INCLINAÇÃO" },
    { pin: "33", color: "Vazio", function: "SEM FUNÇÃO" }
  ],
  "honda-cg-start-160-2022-2023": [
    { pin: "1", color: "Preto/Azul", function: "VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Branco", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO VAI PARA O SENSOR EOT" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL DE SAIDA DO SENSOR TP PARA O ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO 5V SENSOR INCLINAÇÃO E SENSOR TP" },
    { pin: "7", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "8", color: "Marrom", function: "ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "10", color: "Verde", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "11", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA DO SENSOR CKP PARA O ECM" },
    { pin: "13", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "14", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "15", color: "Azul/Preto", function: "VAI PARA O CONECTOR DLC" },
    { pin: "16", color: "Rosa/Verde", function: "ALIMENTAÇÃO NEGATIVA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "21", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "22", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "26", color: "Vermelho/Amarelo", function: "SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM" },
    { pin: "27", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "28", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "29", color: "Verde/Vermelho", function: "SINAL NEGATIVO DO INTERRUPTOR DE EMBREAGEM E PONTO MORTO PARA O ECM" },
    { pin: "30", color: "Amarelo/Verde", function: "VAI PARA O CONECTOR DLC" },
    { pin: "31", color: "Verde", function: "NEGATIVO SENSOR TP" },
    { pin: "32", color: "Verde/Laranja", function: "NEGATIVO SENSOR DE INCLINAÇÃO" },
    { pin: "33", color: "Vazio", function: "SEM FUNÇÃO" }
  ],
  "honda-elite-125-2019-br": [
    { pin: "1", color: "Preto/Azul", function: "VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM" },
    { pin: "2", color: "Verde/Preto", function: "NEGATIVO OU TERRA CHASSI" },
    { pin: "3", color: "Preto/Laranja", function: "SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM" },
    { pin: "4", color: "Verde/Laranja", function: "NEGATIVO VAI PARA O SENSOR TP" },
    { pin: "5", color: "Amarelo/Preto", function: "SINAL SENSOR TP PARA ECM" },
    { pin: "6", color: "Amarelo/Vermelho", function: "ALIMENTAÇÃO SENSOR TP" },
    { pin: "7", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "8", color: "Marrom/Preto", function: "SINAL NEGATIVO ECM PARA BOMBA DE COMBUSTIVEL" },
    { pin: "9", color: "Verde", function: "NEGATIVO OU TERRA CHASSI E TERMINAL DLC" },
    { pin: "10", color: "Verde", function: "NEGATIVO OU TERRA CHASSI E TERMINAL DLC" },
    { pin: "11", color: "Amarelo/Azul", function: "SINAL NEGATIVA ECM PARA BOBINA IGNIÇAO" },
    { pin: "12", color: "Azul/Amarelo", function: "SINAL DE SAIDA DO SENSOR CKP PARA ECM" },
    { pin: "13", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "14", color: "Rosa/Preto", function: "SINAL SENSOR EOT PARA ECM" },
    { pin: "15", color: "Azul/Preto", function: "TERMINAL DLC" },
    { pin: "16", color: "Rosa/Azul", function: "ALIMENTAÇÃO NEGATIVA DA ECM PARA DO BICO INJETOR" },
    { pin: "17", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "18", color: "Azul/Amarelo", function: "INDICADOR LUZ FI PAINEL/ANOMALIA" },
    { pin: "19", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "20", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "21", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "22", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "23", color: "Branco/Amarelo", function: "ALIMENTAÇÃO NEGATIVA SENSOR CKP" },
    { pin: "24", color: "Amarelo/Azul", function: "ALIMENTAÇÃO POSITIVA SENSOR EOT." },
    { pin: "25", color: "Verde/Branco", function: "NEGATIVO CAVALETE LATERAL" },
    { pin: "26", color: "Vazio", function: "SEM FUNÇÃO" },
    { pin: "27", color: "Amarelo/Verde", function: "SEM FUNÇÃO" },
    { pin: "28", color: "Amarelo/Vermelho", function: "SINAL NEGATIVO ECM PARA VALVULA SOLENÓIDE CONTROLE MARCHA LENTA" },
    { pin: "29", color: "Rosa/Branco", function: "SINAL NEGATIVO ECM PARA INTERRUPTOR PARTIDA" },
    { pin: "30", color: "Laranja/Azul", function: "CONECTOR DLC" },
    { pin: "31", color: "Branco/Vermelho", function: "NEGATIVO VAI PARA O SENSOR EOT" },
    { pin: "32", color: "Vermelho/Preto", function: "NEGATIVO VAI PARA O SENSOR IAT" },
    { pin: "33", color: "Marrom/Vermelho", function: "ALIMENTAÇÃO ECU PARA RELÉ PARTIDA" }
  ]
};

let content = fs.readFileSync('src/data/hondaPinouts.ts', 'utf8');
for (const [id, pinout] of Object.entries(updates)) {
  const modelRegex = new RegExp(`(id:\\s*"${id}"[\\s\\S]*?pinout:\\s*)\\[\\]`);
  const pinoutStr = JSON.stringify(pinout, null, 10).replace(/\\n/g, '\\n        ');
  content = content.replace(modelRegex, `$1${pinoutStr}`);
}
fs.writeFileSync('src/data/hondaPinouts.ts', content);
console.log('Batch 2 applied');
