import * as fs from 'fs';
import * as path from 'path';

const file = path.join(process.cwd(), 'src/data/hondaPinouts.ts');
let content = fs.readFileSync(file, 'utf8');

const updates: Record<string, any[]> = {
  "honda-elite-125-2019-2024": [
    { pin: 1, color: ['Preto', 'Branco'], description: 'VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR TP' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL SENSOR TP PARA ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'SINAL NEGATIVO ECM PARA BOMBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI E TERMINAL DLC' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI E TERMINAL DLC' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'SINAL NEGATIVA ECM PARA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL SENSOR EOT PARA ECM' },
    { pin: 15, color: ['Marrom'], description: 'TERMINAL DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DA ECM PARA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'INDICADOR LUZ FI PAINEL/ANOMALIA' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: [], description: 'SEM FUNÇÃO' },
    { pin: 21, color: [], description: 'SEM FUNÇÃO' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Verde'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: ['Verde', 'Branco'], description: 'NEGATIVO CAVALETE LATERAL' },
    { pin: 26, color: [], description: 'SEM FUNÇÃO' },
    { pin: 27, color: [], description: 'SEM FUNÇÃO' },
    { pin: 28, color: ['Amarelo', 'Preto'], description: 'SINAL NEGATIVO ECM PARA VALVULA SOLENÓIDE CONTROLE MARCHA LENTA' },
    { pin: 29, color: ['Verde', 'Branco'], description: 'SINAL NEGATIVO PARA INTERRUPTOR PARTIDA' },
    { pin: 30, color: ['Verde', 'Vermelho'], description: 'CONECTOR DLC' },
    { pin: 31, color: ['Verde'], description: 'NEGATIVO VAI PARA O SENSOR EOT' },
    { pin: 32, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR IAT' },
    { pin: 33, color: ['Marrom', 'Branco'], description: 'ALIMENTAÇÃO ECU PARA RELÉ PARTIDA' }
  ],
  "honda-fan-150-2015": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Branco'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR EOT, MAP, O2 E IAT' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DE CARGA' },
    { pin: 8, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA BOMBA COBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Azul', 'Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: [], description: 'SINAL PWM PARA AQUECEDOR SENSOR OXIGENIO' },
    { pin: 23, color: ['Amarelo'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'LUZ ALC DO PAINEL' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/DIODO/NEUTRO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-lead-110-2009-2010": [
    { pin: 1, color: ['Preto'], description: 'VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR ECT, MAP, TP, IAT' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR MAP E TP' },
    { pin: 7, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA COMBUSTIVEL' },
    { pin: 8, color: ['Verde', 'Vermelho'], description: 'VAI PARA O RELE PARTIDA' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 10, color: [], description: 'SEM FUNÇÃO' },
    { pin: 11, color: ['Amarelo', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'NEGATIVO SENSOR CKP' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL SENSOR IAT' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'PULSO NEGATIVO DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Vermelho'], description: 'VALVULA IACV 2A' },
    { pin: 21, color: ['Verde', 'Vermelho'], description: 'VALVULA IACV 1A' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'SINAL POSITIVO SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Azul'], description: 'SINAL SENSOR ECT' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: [], description: 'SEM FUNÇÃO' },
    { pin: 27, color: ['Amarelo', 'Vermelho'], description: 'SINAL SENSOR MAP' },
    { pin: 28, color: [], description: 'SEM FUNÇÃO' },
    { pin: 29, color: ['Verde', 'Branco'], description: 'INTERRUPTOR DE PARTIDA' },
    { pin: 30, color: ['Laranja'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Preto', 'Vermelho'], description: 'VALVULA IACV 2B' },
    { pin: 32, color: ['Cinza', 'Preto'], description: 'VALVULA IACV 1B' },
    { pin: 33, color: ['Laranja', 'Preto'], description: 'VALVULA SOLENOIDE PVC' }
  ],
  "honda-lead-110-2011": [
    { pin: 1, color: ['Preto'], description: 'VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR ECT, MAP,TP, IAT' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR MAP E TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 10, color: [], description: 'SEM FUNÇÃO' },
    { pin: 11, color: ['Amarelo', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'NEGATIVO SENSOR CKP' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL SENSOR IAT' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'PULSO NEGATIVO DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Vermelho'], description: 'VALVULA IACV 2A' },
    { pin: 21, color: ['Laranja', 'Verde'], description: 'VALVULA IACV 1A' },
    { pin: 22, color: ['Laranja', 'Preto'], description: 'VALVULA SOLENOIDE PVC' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'SINAL POSITIVO SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'SINAL SENSOR ECT' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Amarelo', 'Vermelho'], description: 'SINAL SENSOR MAP' },
    { pin: 27, color: [], description: 'SEM FUNÇÃO' },
    { pin: 28, color: [], description: 'SEM FUNÇÃO' },
    { pin: 29, color: ['Verde', 'Amarelo'], description: 'INTERRUPTOR DE PARTIDA' },
    { pin: 30, color: ['Verde', 'Laranja'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Preto', 'Vermelho'], description: 'VALVULA IACV 2B' },
    { pin: 32, color: ['Cinza', 'Preto'], description: 'VALVULA IACV 1B' },
    { pin: 33, color: ['Verde', 'Vermelho'], description: 'VAI PARA O RELE PARTIDA' }
  ],
  "honda-lead-110-2012-2014": [
    { pin: 1, color: ['Preto'], description: 'VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Laranja'], description: 'NEGATIVO VAI PARA O SENSOR ECT, TP, IAT' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR MAP E TP' },
    { pin: 7, color: [], description: 'SEM FUNÇÃO' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DA BOMBA COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO TERRA/CHASSI' },
    { pin: 10, color: [], description: 'SEM FUNÇÃO' },
    { pin: 11, color: ['Amarelo', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'NEGATIVO SENSOR CKP' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL SENSOR IAT' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'PULSO NEGATIVO DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: [], description: 'SEM FUNÇÃO' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Vermelho'], description: 'VALVULA IACV 2A' },
    { pin: 21, color: ['Laranja', 'Verde'], description: 'VALVULA IACV 1A' },
    { pin: 22, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'SINAL POSITIVO SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'SINAL SENSOR ECT' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: [], description: 'SEM FUNÇÃO' },
    { pin: 27, color: ['Amarelo', 'Vermelho'], description: 'SINAL SENSOR MAP' },
    { pin: 28, color: ['Laranja', 'Preto'], description: 'VALVULA SOLENOIDE PVC' },
    { pin: 29, color: ['Verde', 'Amarelo'], description: 'INTERRUPTOR DE PARTIDA' },
    { pin: 30, color: ['Verde', 'Laranja'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Preto', 'Vermelho'], description: 'VALVULA IACV 2B' },
    { pin: 32, color: ['Cinza', 'Preto'], description: 'VALVULA IACV 1B' },
    { pin: 33, color: ['Verde', 'Vermelho'], description: 'VAI PARA O RELE PARTIDA' }
  ],
  "honda-nx-400i-falcon-2013-2014": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'VOLTAGEM PÓS CHAVE DA BATERIA PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Laranja'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR EOT, TP, O2 E SENSOR IAT.' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO 5V SENSOR MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'PULSO DO TACOMETRO DO PAINEL.' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'VAI PARA RELE DA BOBA DE COMBUSTIVEL' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Azul', 'Branco'], description: 'VAI PARA O CONECTOR DLC E LUZ ABS' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Verde'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'PULSO PWM AQUECEDOR DO SENSOR OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'SINAL SENSOR EOT.' },
    { pin: 25, color: ['Verde', 'Branco'], description: 'SINAL NEGATIVO DO INTERRUPTOR EMBREAGEM/CAVALETE LATERAL.' },
    { pin: 26, color: ['Amarelo', 'Rosa'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Vermelho'], description: 'SINAL DE SAIDA DO SENSOR MAP DA UNIDADE DE SENSORES PARA O ECM' },
    { pin: 28, color: ['Vermelho', 'Amarelo'], description: 'SINAL VALVULA SOLENÓIDE DE CONTROLE PAIR' },
    { pin: 29, color: ['Laranja', 'Amarelo'], description: 'LUZ DO NEUTRO/RELE/DIODO' },
    { pin: 30, color: ['Verde', 'Laranja'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-nxr-150-bros-2009": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'PÓS CHAVE 12V PARA O ECM' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Branco'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR DE INCLINAÇÃO, EOT, MAP E IAT.' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR INCLINAÇÃO, MAP E TP.' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DISTRIBUIDOR DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVE' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Azul', 'Branco'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: [], description: 'SEM FUNÇÃO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Amarelo', 'Azul'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Vermelho', 'Branco'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: [], description: 'SEM FUNÇÃO' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'SINAL NEGATIVO DO INTERRUPTOR DE EMBREAGEM E PONTO MORTO PARA O ECM' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-nxr-150-bros-mix-2010": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'POSITIVO 12V PÓS CHAVE' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Branco'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR DE INCLINAÇÃO, EOT, MAP, O² E SENSOR IAT' },
    { pin: 5, color: ['Amarelo'], description: 'SINAL DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR INCLINAÇÃO, MAP E TP.' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DISTRIBUIDOR DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVE' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL PULSO DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'SINAL PWM AQUECEDOR SENSOR OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Rosa', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'INDICADOR LAMPADA ALC' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'INTERRUPTOR EMBREAGEM/INTERRUPTOR PONTO MORTO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: ['Rosa', 'Preto'], description: 'LUZ MIX SINAL NEGATIVO' }
  ],
  "honda-nxr-150-bros-2011-2012": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'POSITIVO 12V PÓS CHAVE' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Branco'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR DE INCLINAÇÃO, EOT, MAP E SENSOR IAT' },
    { pin: 5, color: ['Amarelo'], description: 'VOLTAGEM DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR INCLINAÇÃO, MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DISTRIBUIDOR DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVE' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL PULSO DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT DA UNIDADE DE SENSORES PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'SINAL PWM AQUECEDOR SENSOR OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Vermelho', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP DA UNIDADE DE SENSORES PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'INDICADOR LAMPADA ALC' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'LUZ NEUTRO/TERRA RELE PARTIDA/DIODO NEUTRO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ],
  "honda-nxr-150-bros-2012-2014": [
    { pin: 1, color: ['Preto', 'Azul'], description: 'POSITIVO 12V PÓS CHAVE' },
    { pin: 2, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 3, color: ['Preto', 'Branco'], description: 'SINAL DE SAIDA DO SENSOR DE OXIGENIO PARA A ECM' },
    { pin: 4, color: ['Verde', 'Branco'], description: 'NEGATIVO VAI PARA O SENSOR DE INCLINAÇÃO, EOT, MAP, O² E SENSOR IAT' },
    { pin: 5, color: ['Amarelo'], description: 'VOLTAGEM DE SAIDA DO SENSOR TP PARA O ECM' },
    { pin: 6, color: ['Amarelo', 'Vermelho'], description: 'ALIMENTAÇÃO SENSOR INCLINAÇÃO, MAP E TP' },
    { pin: 7, color: ['Marrom'], description: 'ALIMENTAÇÃO NEGATIVA DO RELÉ DISTRIBUIDOR DE CARGA' },
    { pin: 8, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO NEGATIVA DA BOMBA DE COMBUSTIVE' },
    { pin: 9, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 10, color: ['Verde'], description: 'NEGATIVO OU TERRA CHASSI' },
    { pin: 11, color: ['Rosa', 'Azul'], description: 'ALIMENTAÇÃO NEGATIVA BOBINA IGNIÇÃO' },
    { pin: 12, color: ['Amarelo'], description: 'SINAL PULSO DO SENSOR CKP PARA O ECM' },
    { pin: 13, color: [], description: 'SEM FUNÇÃO' },
    { pin: 14, color: ['Cinza', 'Azul'], description: 'SINAL DE SAIDA DO SENSOR IAT DA UNIDADE DE SENSORES PARA O ECM' },
    { pin: 15, color: ['Rosa', 'Azul'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 16, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA DO BICO INJETOR' },
    { pin: 17, color: [], description: 'SEM FUNÇÃO' },
    { pin: 18, color: ['Azul', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA LUZ DE ANOMALIA (MIL) PAINEL' },
    { pin: 19, color: [], description: 'SEM FUNÇÃO' },
    { pin: 20, color: ['Marrom', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2A' },
    { pin: 21, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1A' },
    { pin: 22, color: ['Branco', 'Preto'], description: 'SINAL PWM PARA AQUECEDOR SENSOR OXIGENIO' },
    { pin: 23, color: ['Amarelo', 'Branco'], description: 'ALIMENTAÇÃO NEGATIVA SENSOR CKP' },
    { pin: 24, color: ['Rosa', 'Branco'], description: 'ALIMENTAÇÃO POSITIVA SENSOR EOT.' },
    { pin: 25, color: [], description: 'SEM FUNÇÃO' },
    { pin: 26, color: ['Vermelho', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR DE INCLINAÇÃO PARA O ECM' },
    { pin: 27, color: ['Amarelo', 'Verde'], description: 'SINAL DE SAIDA DO SENSOR MAP DA UNIDADE DE SENSORES PARA O ECM' },
    { pin: 28, color: ['Verde', 'Rosa'], description: 'INDICADOR LAMPADA ALC' },
    { pin: 29, color: ['Verde', 'Vermelho'], description: 'LUZ NEUTRO/TERRA RELE PARTIDA/DIODO NEUTRO' },
    { pin: 30, color: ['Marrom', 'Preto'], description: 'VAI PARA O CONECTOR DLC' },
    { pin: 31, color: ['Marrom', 'Vermelho'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 2B' },
    { pin: 32, color: ['Azul', 'Preto'], description: 'ALIMENTAÇÃO ATUADOR MARCHA LENTA (IACV) 1B' },
    { pin: 33, color: [], description: 'SEM FUNÇÃO' }
  ]
};

for (const [id, pinout] of Object.entries(updates)) {
  const searchRegex = new RegExp(`(id: "${id}",[\\s\\S]*?name: "Módulo de Injeção Eletrônica \\(ECM\\)",\\s*pinout: )\\[\\]`);
  
  const pinoutStr = "[\n" + pinout.map(p => {
    return `          { pin: ${p.pin}, color: ${JSON.stringify(p.color)}, description: ${JSON.stringify(p.description)} }`;
  }).join(",\n") + "\n        ]";

  content = content.replace(searchRegex, `$1${pinoutStr}`);
}

fs.writeFileSync(file, content);
console.log("Done updating pinouts batch 3.");
